### ISSUE TITLE
Not finding UI Lib

### ISSUE THREAD

**Issue by YoMamaLlama1** [deltanedas/pictocanvas#2]
![Screenshot_20230419-110648](https://user-images.githubusercontent.com/79997495/233119021-47ed9cdb-a726-4daf-8499-0b318c80838d.png)
After installing pic to canvas, it does not seem to be able to find UI lib, even though it is installed and enabled. This issue does not occur with the pictologic mod however. 
![Screenshot_20230419-110529](https://user-images.githubusercontent.com/79997495/233118765-4dd480f8-8d9e-4670-bb79-01acd1fc7f85.png)

**Comment by deltanedas** [comment]
fine ill change
